[tool.poetry]
name = "sidekickai"
version = "1.0.0"
description = "accelerate with LLM"
authors = ["yasar <yasar.kundottil@gyanai.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.8"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
